#!/usr/bin/env python

import os, getpass

modulepath = '/afs/cern.ch/user/m/mmarinan/SimulationProduction'
os.environ["SIMPRODPATH"] = modulepath

simoutput = '/eos/lhcb/user/m/mmarinan/SimulationJobs'
if simoutput is None :
	simoutput = os.getenv("HOME")+"/SimulationJobs"
os.system("mkdir -p "+simoutput)
os.environ["SIMOUTPUT"] = simoutput

log_simoutput = '/afs/cern.ch/work/m/mmarinan/SimulationJobs'
if log_simoutput is None :
	user = getpass.getuser()
	log_simoutput = "/afs/cern.ch/work/{0}/{1}".format( user[0], user )
os.system("mkdir -p "+log_simoutput)
os.environ["LOG_SIMOUTPUT"] = log_simoutput

from simprod.simjob import *
from IPython import start_ipython
from traitlets.config.loader import Config

if __name__ == "__main__" :

	banner1  = '\n\n'
	banner1 += green(' Welcome on the mini LHCb simulation production framework!\n')
	banner1 += '\n'
	banner1 += green(' author: Matthieu Marinangeli, matthieu.marinangeli@cern.ch.\n')
	
	banner2  = 'production directory: {0}\n'.format(simoutput)

	config = Config()
	
	config.TerminalInteractiveShell.banner1 = banner1
	config.TerminalInteractiveShell.banner2 = banner2
		
		
	jobs = JobCollection()
		
	_vars = globals().copy()
	_vars.update( locals() )

	start_ipython ( argv = [] , user_ns = _vars, config= config )

	jobs._update()
		
	DATABASE.close()
		
	print(blue("\n\t Bye Bye.\n"))
